import prod from './prod.avif'; 
export { prod };
import workspace from './workspace-showroom-banner.jpg';
export { workspace };
import pasted from './pasted-image-0-4.png'
export { pasted };
import dragdrop from './images.gif';
export { dragdrop };
import security from './b74905e1.jpg'
export { security };